# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainCapTool.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(2099, 909)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks|QtWidgets.QMainWindow.GroupedDragging)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.detailTab = QtWidgets.QTabWidget(self.centralwidget)
        self.detailTab.setStyleSheet("")
        self.detailTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.detailTab.setIconSize(QtCore.QSize(30, 30))
        self.detailTab.setElideMode(QtCore.Qt.ElideNone)
        self.detailTab.setTabsClosable(False)
        self.detailTab.setMovable(True)
        self.detailTab.setTabBarAutoHide(False)
        self.detailTab.setObjectName("detailTab")
        self.controlTab = QtWidgets.QWidget()
        self.controlTab.setObjectName("controlTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.controlTab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.controlTab)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(333, 16777215))
        self.lineEdit_2.setStyleSheet("background-color: rgb(80, 95, 105);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.controlTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(1200, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setIndent(-1)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 9, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(225, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(333, 16777215))
        self.lineEdit.setStyleSheet("background-color: rgb(80, 95, 105);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 2)
        self.displayTagsComboBox = QtWidgets.QComboBox(self.controlTab)
        self.displayTagsComboBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.displayTagsComboBox.setFont(font)
        self.displayTagsComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.displayTagsComboBox.setObjectName("displayTagsComboBox")
        self.displayTagsComboBox.addItem("")
        self.displayTagsComboBox.addItem("")
        self.displayTagsComboBox.addItem("")
        self.gridLayout.addWidget(self.displayTagsComboBox, 0, 5, 1, 1)
        self.ercotCheckBox = QtWidgets.QCheckBox(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ercotCheckBox.sizePolicy().hasHeightForWidth())
        self.ercotCheckBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ercotCheckBox.setFont(font)
        self.ercotCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ercotCheckBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.ercotCheckBox.setTristate(False)
        self.ercotCheckBox.setObjectName("ercotCheckBox")
        self.gridLayout.addWidget(self.ercotCheckBox, 0, 3, 2, 1)
        self.pushButton = QtWidgets.QPushButton(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setWhatsThis("")
        self.pushButton.setStyleSheet("border-color: rgb(175, 203, 203);\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 4)
        self.detailYOY = QtWidgets.QTableView(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detailYOY.sizePolicy().hasHeightForWidth())
        self.detailYOY.setSizePolicy(sizePolicy)
        self.detailYOY.setMinimumSize(QtCore.QSize(1200, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.detailYOY.setFont(font)
        self.detailYOY.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.detailYOY.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.detailYOY.setDragEnabled(True)
        self.detailYOY.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.detailYOY.setSortingEnabled(True)
        self.detailYOY.setObjectName("detailYOY")
        self.gridLayout.addWidget(self.detailYOY, 1, 4, 6, 8)
        self.label_2 = QtWidgets.QLabel(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(32, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 4)
        self.capTags = QtWidgets.QTableView(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capTags.sizePolicy().hasHeightForWidth())
        self.capTags.setSizePolicy(sizePolicy)
        self.capTags.setMinimumSize(QtCore.QSize(385, 300))
        self.capTags.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.capTags.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.capTags.setDragEnabled(True)
        self.capTags.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.capTags.setSortingEnabled(True)
        self.capTags.setObjectName("capTags")
        self.gridLayout.addWidget(self.capTags, 5, 0, 1, 4)
        self.capTagGraph = QtWidgets.QWidget(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.capTagGraph.sizePolicy().hasHeightForWidth())
        self.capTagGraph.setSizePolicy(sizePolicy)
        self.capTagGraph.setMaximumSize(QtCore.QSize(415, 16777215))
        self.capTagGraph.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.capTagGraph.setObjectName("capTagGraph")
        self.graphLayout = QtWidgets.QVBoxLayout(self.capTagGraph)
        self.graphLayout.setObjectName("graphLayout")
        self.gridLayout.addWidget(self.capTagGraph, 6, 0, 1, 4)
        self.timeStampCheckBox3 = QtWidgets.QCheckBox(self.controlTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.timeStampCheckBox3.setFont(font)
        self.timeStampCheckBox3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.timeStampCheckBox3.setObjectName("timeStampCheckBox3")
        self.gridLayout.addWidget(self.timeStampCheckBox3, 0, 7, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.controlTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 4)
        self.timeStampCheckBox1 = QtWidgets.QCheckBox(self.controlTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.timeStampCheckBox1.setFont(font)
        self.timeStampCheckBox1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.timeStampCheckBox1.setObjectName("timeStampCheckBox1")
        self.gridLayout.addWidget(self.timeStampCheckBox1, 0, 6, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.detailTab.addTab(self.controlTab, "")
        self.detailTab2 = QtWidgets.QWidget()
        self.detailTab2.setObjectName("detailTab2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.detailTab2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.detailTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 2)
        self.meterValuePR = QtWidgets.QTableView(self.detailTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meterValuePR.sizePolicy().hasHeightForWidth())
        self.meterValuePR.setSizePolicy(sizePolicy)
        self.meterValuePR.setMinimumSize(QtCore.QSize(300, 192))
        self.meterValuePR.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.meterValuePR.setDragEnabled(True)
        self.meterValuePR.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.meterValuePR.setSortingEnabled(True)
        self.meterValuePR.setObjectName("meterValuePR")
        self.gridLayout_2.addWidget(self.meterValuePR, 1, 1, 1, 2)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.detailTab2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.comboBoxMRHists = QtWidgets.QComboBox(self.detailTab2)
        self.comboBoxMRHists.setObjectName("comboBoxMRHists")
        self.comboBoxMRHists.addItem("")
        self.comboBoxMRHists.addItem("")
        self.comboBoxMRHists.addItem("")
        self.gridLayout_6.addWidget(self.comboBoxMRHists, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.detailTab2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.meterReadPR = QtWidgets.QTableView(self.detailTab2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meterReadPR.sizePolicy().hasHeightForWidth())
        self.meterReadPR.setSizePolicy(sizePolicy)
        self.meterReadPR.setMinimumSize(QtCore.QSize(665, 192))
        self.meterReadPR.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.meterReadPR.setDragEnabled(True)
        self.meterReadPR.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.meterReadPR.setSortingEnabled(True)
        self.meterReadPR.setObjectName("meterReadPR")
        self.gridLayout_2.addWidget(self.meterReadPR, 1, 0, 1, 1)
        self.detailTab.addTab(self.detailTab2, "")
        self.detailedViewTab = QtWidgets.QWidget()
        self.detailedViewTab.setObjectName("detailedViewTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.detailedViewTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mplwindow = QtWidgets.QWidget(self.detailedViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplwindow.sizePolicy().hasHeightForWidth())
        self.mplwindow.setSizePolicy(sizePolicy)
        self.mplwindow.setMinimumSize(QtCore.QSize(0, 500))
        self.mplwindow.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.mplwindow.setObjectName("mplwindow")
        self.layoutDV = QtWidgets.QVBoxLayout(self.mplwindow)
        self.layoutDV.setObjectName("layoutDV")
        self.gridLayout_4.addWidget(self.mplwindow, 0, 1, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.detailedViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
        self.acctDetailTableView = QtWidgets.QTableView(self.detailedViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acctDetailTableView.sizePolicy().hasHeightForWidth())
        self.acctDetailTableView.setSizePolicy(sizePolicy)
        self.acctDetailTableView.setMinimumSize(QtCore.QSize(0, 300))
        self.acctDetailTableView.setMaximumSize(QtCore.QSize(16777215, 400))
        self.acctDetailTableView.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.acctDetailTableView.setObjectName("acctDetailTableView")
        self.gridLayout_4.addWidget(self.acctDetailTableView, 2, 1, 1, 1)
        self.accts2Plot = QtWidgets.QListWidget(self.detailedViewTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accts2Plot.sizePolicy().hasHeightForWidth())
        self.accts2Plot.setSizePolicy(sizePolicy)
        self.accts2Plot.setMaximumSize(QtCore.QSize(350, 16777215))
        self.accts2Plot.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.accts2Plot.setObjectName("accts2Plot")
        self.gridLayout_4.addWidget(self.accts2Plot, 1, 0, 2, 1)
        self.detailTab.addTab(self.detailedViewTab, "")
        self.tagsYOYtab = QtWidgets.QWidget()
        self.tagsYOYtab.setObjectName("tagsYOYtab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tagsYOYtab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.capTagsYOY = QtWidgets.QTableView(self.tagsYOYtab)
        self.capTagsYOY.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.capTagsYOY.setDragEnabled(True)
        self.capTagsYOY.setSortingEnabled(True)
        self.capTagsYOY.setObjectName("capTagsYOY")
        self.gridLayout_3.addWidget(self.capTagsYOY, 0, 0, 1, 1)
        self.detailTab.addTab(self.tagsYOYtab, "")
        self.transTagsYOYtab = QtWidgets.QWidget()
        self.transTagsYOYtab.setObjectName("transTagsYOYtab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.transTagsYOYtab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.transTagsYOY = QtWidgets.QTableView(self.transTagsYOYtab)
        self.transTagsYOY.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.transTagsYOY.setObjectName("transTagsYOY")
        self.horizontalLayout.addWidget(self.transTagsYOY)
        self.detailTab.addTab(self.transTagsYOYtab, "")
        self.capacityTab = QtWidgets.QWidget()
        self.capacityTab.setObjectName("capacityTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.capacityTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.capacityTab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.capacity = QtWidgets.QTableView(self.capacityTab)
        self.capacity.setStyleSheet("background-color: rgb(6, 30, 38);")
        self.capacity.setDragEnabled(True)
        self.capacity.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.capacity.setSortingEnabled(True)
        self.capacity.setObjectName("capacity")
        self.verticalLayout_2.addWidget(self.capacity)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.detailTab.addTab(self.capacityTab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setStyleSheet("background-color: rgb(6, 30, 38);\n"
"color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_5.addWidget(self.textBrowser)
        self.detailTab.addTab(self.tab, "")
        self.Documentation = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Documentation.setFont(font)
        self.Documentation.setObjectName("Documentation")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Documentation)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.webEngineViewPDF = QtWebEngineWidgets.QWebEngineView(self.Documentation)
        self.webEngineViewPDF.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineViewPDF.setObjectName("webEngineViewPDF")
        self.verticalLayout_3.addWidget(self.webEngineViewPDF)
        self.detailTab.addTab(self.Documentation, "")
        self.verticalLayout.addWidget(self.detailTab)
        self.summFooter = QtWidgets.QLabel(self.centralwidget)
        self.summFooter.setAlignment(QtCore.Qt.AlignCenter)
        self.summFooter.setObjectName("summFooter")
        self.verticalLayout.addWidget(self.summFooter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 2099, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menuBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionQuit.setFont(font)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAddList = QtWidgets.QAction(MainWindow)
        self.actionAddList.setObjectName("actionAddList")
        self.actionPlot = QtWidgets.QAction(MainWindow)
        self.actionPlot.setObjectName("actionPlot")
        self.actionPercent_Change_Calc = QtWidgets.QAction(MainWindow)
        self.actionPercent_Change_Calc.setObjectName("actionPercent_Change_Calc")
        self.menuFile.addAction(self.actionQuit)
        self.menuTools.addAction(self.actionPercent_Change_Calc)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.detailTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Analytics Tool"))
        self.label_10.setText(_translate("MainWindow", "Choose Tags To Display:"))
        self.label_4.setText(_translate("MainWindow", "                                                                                 Account Detail"))
        self.displayTagsComboBox.setItemText(0, _translate("MainWindow", "Current PY CapTag"))
        self.displayTagsComboBox.setItemText(1, _translate("MainWindow", "Future PY CapTags"))
        self.displayTagsComboBox.setItemText(2, _translate("MainWindow", "All CapTags"))
        self.ercotCheckBox.setText(_translate("MainWindow", " ERCOT "))
        self.ercotCheckBox.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.pushButton.setText(_translate("MainWindow", "Click To Produce Capacity Tags"))
        self.label_2.setText(_translate("MainWindow", "Revision# :"))
        self.label.setText(_translate("MainWindow", "PR# :"))
        self.pushButton_2.setText(_translate("MainWindow", "Copy OFFER_% to Clipboard"))
        self.timeStampCheckBox3.setText(_translate("MainWindow", "  Ch3-TS:"))
        self.label_3.setText(_translate("MainWindow", "Current PR: "))
        self.timeStampCheckBox1.setText(_translate("MainWindow", "Ch1-TS"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.controlTab), _translate("MainWindow", "Control"))
        self.label_7.setText(_translate("MainWindow", "Forecasted Annual Values:"))
        self.label_6.setText(_translate("MainWindow", "Meter Reads:"))
        self.comboBoxMRHists.setItemText(0, _translate("MainWindow", "12 Months"))
        self.comboBoxMRHists.setItemText(1, _translate("MainWindow", "36 Months"))
        self.comboBoxMRHists.setItemText(2, _translate("MainWindow", "60 Months"))
        self.label_8.setText(_translate("MainWindow", "Data History:"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.detailTab2), _translate("MainWindow", "Detail"))
        self.label_9.setText(_translate("MainWindow", "Select Account"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.detailedViewTab), _translate("MainWindow", "Detailed View"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.tagsYOYtab), _translate("MainWindow", "CapTags YOY"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.transTagsYOYtab), _translate("MainWindow", "TransTags YOY"))
        self.label_5.setText(_translate("MainWindow", "OVERALL DATA"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.capacityTab), _translate("MainWindow", "Tags Data"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">Tag Tool</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600;\">Developed By: Jose Alvarez</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; text-decoration: underline;\">For any issues, bugs, data/tables not loading or refreshing, please email at jose.alvarez@engie.com with more details about the error, including the PR and Revision number that caused the error.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Control Tab:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Here, you input the desired PR and Revision #. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">One has either the option to press enter from their keyboard, or click the button the button that says &quot;Click To Produce Capacity Tags&quot;.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Upon clicking, the OFFER_% code for the PR inputed will be copied automatically to the clipboard for input into CCS. For ease of use, one has the option  click the button underneath, &quot;Copy OFFER_% to Clipboard&quot;.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If there is no existing PR and Rev# combination, blank tables and the application will advise you to verify the information inputted.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The following is achieved every time a PR and Rev# are searched.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">On the left, the Planning Year, Capacity Tags, Transmission Tags, and Account quantity are displayed. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">A visual of the Capacity Tags YOY is depicted in the graph on the bottom left corner.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">to be continued ...</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">VERSION 46 UPDATES:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Obtaining meter reads and parsing through data was substantially improved/optimized. Therefore, loading time for this data should be minimized.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Detailed view tab loading times to generate graph by meters was also optimized. While it would take seconds, sometimes minutes to get this data, now it only takes less than a second to load &amp; generate a graph.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Added shortcut on Control tab to display/hide tabs based on different criteria: (Current PY tags, Future PY tags, All tags). This allows the user to compare historical and future tags to Forecast values and SCA values.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 36 Updates:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - The plots are now being computed in the &quot;Detailed View&quot; tab. This is done by either clicking on the left side on the wanted account to display its information.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - There is also a shortcut available by either right clicking on any other table on the respective row for the account you want a more \'Detailed View\' of and pressing &quot;More Info&quot; on the right-click context menu, or simply by pressing Shift+Z.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 35 Updates: (12/31/2019):</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Implementation for a more detailed view of each individual account is progressively being added on a new tab called &quot;Detailed View&quot;</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        - Currently, an algorithm was developed to only find data for each specific account, including the current Forecasted Peak kW, the Capacity Tag for each year, and the Summer Peaks from Meter Reads.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        - A shortcut was added by right clicking on other tables on the desired Account ID# which will facilitate the ability to navigate through tabs as well as looking for a more &quot;Detailed&quot; View.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">            - This shortcut  will be changed to be able to detect the account ID depending on the row you\'re at, rather than only the Account ID column on each table.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Fixed bug when quering from the  Meter Values table on TPPE when looking for the Forecasted Annual Values caused by the new year (2020) approaching and the program filtering by current year.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        - This may bring up issues, please contact me if there\'s any problems when using the tool.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 29/30 Updates: (12/09/2019):</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Fixed Bug on Meter Reads table that gave the wrong Summer Peak value on rare occasions.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Fixed Issue that wasn\'t coloring Captag to Summer Peak Variances when Forecasted Peak was &lt; 100kW and variance &gt; 10%</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 28 Updates: (12/06/2019):</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Removed &quot;Noise&quot; to have more concise flags and error alerts.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 27 Updates: (12/05/2019):</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Fixed Bug on Account Details Table. Please contact Jose Alvarez if any issues arise in this table after this update.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 26 Updates: (12/04/2019)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Fixed updates from Version 24 that was causing duplicate reads to be eliminated through entire table, not distinctively grouped by meter.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Added validation for non - lighting accounts. This will highlight entire row purple if there exists a Capacity Tag = 0, and the account is not classified as lighting (LIGHTING, LITE, ROLA, TL, SL, OL, DEEMED) in the Profile Code column.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 25 Updates: (12/03/2019)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Added Error Handling preventions and alerts.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 24 Updates: (12/02/2019)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Added functionality on Meter Reads table that prevents duplicate meter reads from showing, which therefore fixes SCA to Forecasted Annual kWh Variances on certain occurrences. (Fixed 12/04/2019)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 23 Updates:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Fixed Bug that was causing the Forecasted Annual Values table not to load on the Detail Tab.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 22 Updates:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Percent Change Calculator added to &quot;Right-Click&quot; Context Menu, and Tools Section on the Ribbon.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - ERCOT Implementation in the Detail tab displaying SCA data, and Forecasted data.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Entire row will be highlighted Magenta in the Control tab -&gt; Account Detail Table, and  Detail tab -&gt; Forecasted Annual Values table if the Forecasted</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">        Annual kWh Usage/ meter = 0, or if the SCA Total Usage/ meter = 0.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Delta Day Count SCA data added in Control tab -&gt; Account Detail Table.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 21 Updates:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Load-Weighted averages are now being computed in the GRANT TOTAL ROW in the Control tab -&gt; Account Detail Table.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 20 Updates:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The Meter Reads Table was modified to display more information.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Start Read Time &amp; Stop Read Time: mm/dd/yyyy format to have a more accurate date on meter read.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    - Delta Day Count: Days between Start and Stop Read dates.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.tab), _translate("MainWindow", "Information"))
        self.detailTab.setTabText(self.detailTab.indexOf(self.Documentation), _translate("MainWindow", "Documentation"))
        self.summFooter.setText(_translate("MainWindow", "           Sum: 0        Count: 0        Avg: 0"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAddList.setText(_translate("MainWindow", "Add to Plot List"))
        self.actionPlot.setText(_translate("MainWindow", "Plot"))
        self.actionPercent_Change_Calc.setText(_translate("MainWindow", "Percent Change Calculator"))

from PyQt5 import QtWebEngineWidgets

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

